= USAGE GUIDE

Above is example of top level heading. This is referenced for navigation (previous/next) of the pages in rendered training content.

Use this page as reference of the syntax for content drafting. 
Delete this page while publishing the course.

== Second level heading

=== Third level heading

Normal text.
Write the text with *Bold* or _Italic_, font.
You may also use `commands in back ticks` as per requirement.

Add the text with gap of a line for new paragraph.

You may also use hard line breaks  +
for new line in single paragraph.

. Numbered Step 1 
. Numbered Step 2
+
[source,bash,role=execute]
----
Code block for command with copy button.
----
+
.Sample Output
----
Code block to show sample output of the command.
This does not have copy button.
----

. Numbered Step 3
  .. Sub Numbered Step 1
  .. Sub Numbered Step 2


* Bullet list item 1
* Bullet list item 2
  ** Sub Bullet list item 1
  ** Sub Bullet list item 2
* Bullet list item 3

NOTE: Highlighted text for note Callout

WARNING: Highlighted text for warning Callout

See below link on Left to navigate to previous page and on Right to navigate to the next page. These are headers of those respective pages.
